### Generated by rprotoc. DO NOT EDIT!
require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Spec
  module Proto
    class ResourceFindRequest < ::Protobuf::Message
      optional :String, :name, 1
      optional :bool, :active, 2
    end
    class Resource < ::Protobuf::Message
      optional :String, :name, 1
      optional :int32, :status, 2
    end
  end
end